name: Plugin check action

on: [push, pull_request, release]

jobs:
  style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: |
          pip install invoke
          pip install flake8==3.8.3
          pip install pep8-naming==0.11.1
      - name: Style Checks
        run: |
          flake8 .

  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Python Dependencies
        run: |
          pip install --upgrade wheel setuptools twine build
      - name: Build Binary
        run: |
          python3 -m build
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
