name: Plugin check action

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true

env:
  python_version: 3.7

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Install Deps
        run: |
          pip install flake8==5.0.4
          pip install pep8-naming==0.13.1
      - name: Style Checks
        run: |
          flake8 .

  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: style
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Install Python Build Dependencies
        run: |
          pip install --upgrade wheel setuptools twine build
      - name: Build Binary
        run: |
          python3 -m build
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
