# Reusable action for plugins.
# This performs:
# - linting with flake and pep8-naming
# - publishes to PyPi

# Re-use this workflow with a few lines:
####
#on:
#  push:
#    branches: ['main', 'master']
#  pull_request:
#    types: [opened, edited, reopened]
#  release:
#    types: [published]
#jobs:
#  plugin-action:
#    uses: matmair/inventree-meta-plugin/.github/workflows/plugin_action.yml@1.0
#    secrets: inherit
####

name: Plugin check action

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        default: 3.7
        required: false
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install style check dependencies
        run: |
          pip install flake8==5.0.4
          pip install pep8-naming==0.13.1
      - name: Check style
        run: |
          flake8 .

  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: style
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Python build dependencies
        run: |
          pip install --upgrade wheel setuptools twine build
      - name: Build binary
        run: |
          python3 -m build
      - name: Publish tp PyPi
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
